- source/includes/_authentication.md
- source/includes/_briefings.md
- source/includes/_categories.md
- source/includes/_groups.md
- source/includes/_streams.md
- source/includes/_users.md
This can publish once https://github.com/Attensadev/customer-api/pull/74 is deployed.
> owner link in stream and fix http to https links

- source/includes/_briefings.md
- source/includes/_categories.md
- source/includes/_streams.md
- source/includes/_timezones.md
- source/includes/_users.md
- source/index.md
for [#99952898 - POST /streams/{streamId}/briefings](https://www.pivotaltracker.com/story/show/99952898)
> Briefing POST updates

- source/includes/_groups.md
- source/includes/_streams.md
Provides examples for substream list on stream view
This should be delivered concurrently with https://github.com/Attensadev/customer-api/pull/85
> Doc updates for list of substreams in stream view

- source/includes/_streams.md
Documentation for `POST /streams/{streamId}/streams`
Should be deployed concurrently with https://github.com/Attensadev/customer-api/pull/86
> POST substreams to collection streams

- source/includes/_categories.md
Updates categories GET and PUT to support subcategories array.
Should deploy concurrently with https://github.com/Attensadev/customer-api/pull/87
> Documentation for subcategories

- source/includes/_streams.md
Documents bing search streams.
Should deploy concurrently with https://github.com/Attensadev/customer-api/pull/101
[#102216442](https://www.pivotaltracker.com/story/show/102216442)
> Documentation for bing search streams

- source/includes/_streams.md
[#103521364 - Add support for DELETE /streams/{streamId}/streams/{streamId}/](https://www.pivotaltracker.com/story/show/103521364)
> Document endpoint for deleting substream

- source/includes/_users.md
documents DELETE /user/{userId}/streams/{streamId} for removing a users follow/subscribe status on a stream.
[#103594272]
> documents DELETE /user/{userId}/streams/{streamId}

- source/includes/_streams.md
[#105710106 - Add source.uri and source.search query params to /streams](https://www.pivotaltracker.com/story/show/105710106)
> Document source search options

- source/includes/_streams.md
docs for GET /streams/{streamId}/users
> docs for getting stream followers

- source/includes/_templatedata.md
- source/index.md
Added it to the bottom of the page.
> documentation for template briefing data.

- source/includes/_templatedata.md
Made edits to the variable definitions.
> Templatedata

- source/includes/_reports.md
- source/index.md
Doc part of https://www.pivotaltracker.com/story/show/118800433.
> Documentation for /reports endpoint

- source/includes/_streams.md
https://www.pivotaltracker.com/story/show/133145797
> documentation for POST /streams/{streamId}/items/{itemId}/attachments

- source/includes/_templatedata.md
https://www.pivotaltracker.com/story/show/136747195
> Docs for Hostname, recipient, dates and standalone briefing concepts

- source/includes/_templatedata.md
https://www.pivotaltracker.com/story/show/137753867
> Added docs for {{briefing.commentary.title}} and {{briefing.commentary.title}}

- source/includes/_briefings.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/135654751
https://www.pivotaltracker.com/story/show/135732255
> added docs for GET /briefings/{id} and updated GET /briefings

- source/includes/_briefings.md
- source/includes/_streams.md
https://www.pivotaltracker.com/story/show/135653253 https://www.pivotaltracker.com/story/show/135739701
> added documentation for POST /briefings and /PUT /briefings/{id} endpoints

- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/142538811
> added docs for tagIds and categoryIds filters for stream GET's

- source/includes/_users.md
https://www.pivotaltracker.com/story/show/135734241
https://www.pivotaltracker.com/story/show/135734243
> docs for POST /users/{id}/briefings and fix for GET

- source/includes/_briefings.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/136079179
https://www.pivotaltracker.com/story/show/135734237
> docs for DELETE /briefings/{id} and DELETE /users/{id}/briefings{id}

- source/includes/_briefings.md
https://www.pivotaltracker.com/story/show/136079605 https://www.pivotaltracker.com/story/show/135732559
> docs for GET /briefings/{id} streams and users

- source/includes/_briefings.md
- source/includes/_groups.md
https://www.pivotaltracker.com/story/show/136080391 https://www.pivotaltracker.com/story/show/136081007
> docs for DELETE /briefings/{id} streams/{id} and users/{id}

- source/includes/_briefings.md
https://www.pivotaltracker.com/story/show/146182971
> docs for GET /briefings/{briefingId}/preview

- source/includes/_streams.md
https://www.pivotaltracker.com/story/show/144246585
> docs for GET /streams/{streamId}/items

- source/includes/_items.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/144246651
> docs for GET /items and GET /items/{itemId}

- source/index.md
https://www.pivotaltracker.com/story/show/144246651
> added Items section to index

- source/includes/_groups.md
- source/includes/_items.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155137598
> added docs for readers and likes endpoints

- source/includes/_items.md
- source/includes/_streams.md
https://www.pivotaltracker.com/story/show/155266067
> added docs for likedByUser, readByUser and savedByUser in item responses

- source/includes/_items.md
https://www.pivotaltracker.com/story/show/155289587
> docs for includeReadItems and note that GET /items/{id} will mark the item as read 

- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155261967
https://www.pivotaltracker.com/story/show/155365584
> added docs for GET /users/{id}/items and /users/{id}/savedItems

- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155443576
> Docs for POST/DELETE /users/{id}/savedItems endpoints

- source/includes/_items.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155442038
> document modified in item responses and as an item sort option

- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155443576
> adde Request and Response section to delete savedItem docs

- source/includes/_items.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155476571
> docs for Stream.itemLogoUrl and item.logoUrl

- source/includes/_streams.md
https://www.pivotaltracker.com/story/show/155476571
> improved wording for Request properties descriptions for POST/PUT streams

- source/includes/_items.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155576542
> document comments/likes/readers counts in item responses

- source/includes/_items.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155576563
> document includeComments option and comments in item responses

- source/includes/_items.md
https://www.pivotaltracker.com/story/show/155576582
> Documentation for POST and DELETE /items/{itemId}/comments endpoints

- source/includes/_items.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/155821661
> Dcoumnet attentionRank in responses and as a sort option

- Gemfile.lock
https://www.pivotaltracker.com/story/show/162012913
> upgrade to rack 1.6.11 to avoid security vulnerability

- Gemfile.lock
https://www.pivotaltracker.com/story/show/163634000
> upgrade ffi to 1.10.0 to avoid security vulnerability

- source/includes/_groups.md
https://www.pivotaltracker.com/story/show/169848485
> add documentation for Group's autoAddNewUsers

- source/includes/_groups.md
https://www.pivotaltracker.com/story/show/169848485
> remove [] and () pointers and improve formatting of POST /groups aside

- source/includes/_groups.md
https://www.pivotaltracker.com/story/show/169854859
> Auto add user doc group put

- source/includes/_briefings.md
- source/includes/_categories.md
- source/includes/_groups.md
- source/includes/_items.md
- source/includes/_streamTags.md
- source/includes/_streams.md
- source/includes/_users.md
https://www.pivotaltracker.com/story/show/171799084
> changed all occurences of api.attensa.com to api.attensa.net
